name: Deploy do Painel Shiva Parvati

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências e Compilar
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present

      - name: Upload do Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
